In [2]:
# Create a 2x2 numpy array of US and GB deaths in two American Revolutionary War battles
# listed below for US and GB correspondingly (1 point):

import numpy as np

battles = np.array([[344, 2345],
                    [4345, 253]])
print(battles)


[[ 344 2345]
 [4345  253]]


In [3]:
# Select the entries for US deaths (1 point)
# Select the entries for GB deaths (1 point)
# Select the entries for US deaths in the 2nd battle (1 point)

US_deaths = battles[:, 0]

gb_deaths = battles[:, 1]

US_deaths_2nd_battle = battles[1, 0]


print("US Deaths:")
print(US_deaths)

print("\nGB Deaths:")
print(gb_deaths)

print("\nUS Deaths in 2nd Battle:")
print(US_deaths_2nd_battle)




US Deaths:
[ 344 4345]

GB Deaths:
[2345  253]

US Deaths in 2nd Battle:
4345


In [23]:
# Sort this array along the first axis (1 point).

sorted_battles = np.sort(battles, axis=0)

print(sorted_battles)


[[ 344 2345]
 [4345 5347]]


In [13]:
# Sort this array along the second axis (1 point)

sorted_battles = np.sort(battles, axis=1)

print(sorted_battles)


[[ 344 2345]
 [ 253 4345]]


In [14]:
# Swap rows and columns of this array (1 point)

swapped_battles = np.array([[battles[0, 0], battles[1, 0]],
                            [battles[0, 1], battles[1, 1]]])

print(swapped_battles)


[[ 344 4345]
 [2345  253]]


In [15]:
# What is the total number of deaths (including both the US and GB) for the two battles? (1 point)

total_deaths = np.sum(battles)

print(total_deaths)

7287


In [16]:
# What is the average number of deaths in each battle (US and GB combined)? (2 points)

us_deaths_battle1 = 344
gb_deaths_battle1 = 2345
us_deaths_battle2 = 4345
gb_deaths_battle2 = 253

average_deaths_battle_1 = (us_deaths_battle1 + gb_deaths_battle1) / 2
average_deaths_battle_2 = (us_deaths_battle2 + gb_deaths_battle2) / 2

print(average_deaths_battle_1)
print(average_deaths_battle_2)


1344.5
2299.0


In [19]:
# Replace Battle 2 GB deaths in your array to 5347 (1 point)

battles[1,1]=5347
print(battles)

[[ 344 2345]
 [4345 5347]]
